apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qm61ff52j-dotnet-basic
  janus-idp.io/tekton: qm61ff52j-dotnet-basic
  backstage.io/kubernetes-id: qm61ff52j-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qm61ff52j-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
